name: Create Release ZIP

on:
  release:
    types: [created]

jobs:
  create-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Install zip command
      run: sudo apt-get install zip

    - name: Create ZIP file
      run: zip -r cloudflare-tools.zip . -x .git\* .github\* composer.json composer.lock .gitignore

    - name: Upload ZIP to Release
      uses: softprops/action-gh-release@v1
      with:
        files: cloudflare-tools.zip
        name: Create Release Zip

